# ESte workflow hará un buiild de un proyecto Java con Maven, cada vez que se haga push en el repositorio.

name: Prueba GithubActions - Java CI with Maven

on: #Tipo de Evento
  push:
    branches: 
      - feature/* #Solo para las ramas feature  
  commit_comment:
    branches: 
      - feature/* #Solo para las ramas feature  

jobs:
  build-nuestraAplicacion: #nombre del job
    runs-on: ubuntu-latest #Maquina virtual para ejecucion
    steps: #Pasos del job
    - name: Checkout de la rama
      run: echo "Haciendo el chekout..." #Action para hacer log
    - uses: actions/checkout@v4 #Actions para pasar la rama a la maquina virtual de despliegue.
                                #La hemos encontrado en https://github.com/marketplace/actions/checkout 
                                #y se indica la version
     
    - name: Set up JDK 17 #Version java
      uses: actions/setup-java@v3 #Setup y version
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml #Lanza maven

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
